### ISSUE TITLE
salt-cloud doesn't clean up provisioned softlayer VM when bootstrap fails

### ISSUE THREAD

**Issue by michaeldye** [saltstack/salt-cloud#927]
Given the following configs:

```
# cat ./cloud.profiles.d/softlayer.conf 
sl_centos7_small:
  provider: sl
  image: CENTOS_7_64
  cpu_number: 1
  ram: 1024
  disk_size: 25
  local_disk: True
  hourly_billing: True
  domain: domain.tld
  location: hou02
```
```
# cat ./cloud.providers.d/softlayer.conf 
sl:
  minion:
    master: 1.2.3.4
  user: user
  apikey: keykeykeykeykey
  provider: softlayer
  script: bootstrap-salt
  script_args: -Z
```

... if the invocation of `salt-cloud -p sl_centos7_small myvm` fails during bootstrap (in my case b/c `deploy.sh` encountered a yum error:  `http://mirrors.service.networklayer.com/centos/7/os/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found`), the VM will remain provisioned but not under salt management b/c the agent is not installed. The agent key is accepted on the master so remote execution commands will yield errors:

```
# salt 'myvm' state.highstate
  myvm:
      Minion did not return. [Not connected]
```
