### ISSUE TITLE
[EC2][AWS] How to specify static private ip address in map file?

### ISSUE THREAD

**Issue by zanhsieh** [saltstack/salt-cloud#932]
Hi,

Just curious how this could be done. I have tried:

```
base_ec2_test:
  - aws-dummy1.example.com:
      make_master: True
      ipAddress: 192.168.135.100
  - aws-dummy2.example.com:
      ipAddress: 192.168.135.101
```
or
```
...
      private_ips: ['192.168.135.100']
...
      private_ips: ['192.168.135.101']
...
```
Neither them work. EC2 instances launched without obeying map file ip address. My ec2 profile config looks similar like this:
```
base_ec2_public:
  provider: my-ec2-southeast-public-ips
  image: ami-a1b2c3d4
  size: t2.micro
  ssh_username: ec2-user
  del_root_vol_on_destroy: True
  del_all_vol_on_destroy: True

base_ec2_test:
  network_interfaces:
    - DeviceIndex: 0
      PrivateIpAddresses:
        - Primary: True
      #auto assign public ip (not EIP)
      AssociatePublicIpAddress: True
      SubnetId: subnet-b70e8dd2
      SecurityGroupId:
        - sg-24fa6541
  extends: base_ec2_public
```
I have learned to add a PrivateIpAddress after 'Primary: True' would nail down this issue like this:
```
...
  network_interfaces:
    - DeviceIndex: 0
      PrivateIpAddresses:
        - Primary: True
          PrivateIpAddress: 192.168.135.200
...
```
But if I did that I'd have to define / repeat tons of profiles just for the sake of assigning static private ip addresses, plus each instance has to assign to different profile also just for the sake of assigning static private ip. 

Any help would definitely be appreciated.
