### ISSUE TITLE
2015.8.0 salt-cloud documentation or implimentation wrong for del_*on_destroy

### ISSUE THREAD

**Issue by jessicabreck** [saltstack/salt-cloud#936]
The documentation reads as such(https://docs.saltstack.com/en/latest/topics/cloud/aws.html):

```
  volumes:
    - { size: 100, device: /dev/sde, type: gp2 }
    - { size: 100, device: /dev/sdf, type: gp2 }
  del_root_vol_on_destroy: True
  del_all_vols_on_destroy: True
```

If you write a file as above, it ignores these values, and does not delete the EC2 volumes.

If you write the file as follows:

```
  del_root_vol_on_destroy: True
  del_all_vols_on_destroy: True
  volumes:
    - { size: 100, device: /dev/sde, type: gp2 }
    - { size: 100, device: /dev/sdf, type: gp2 }
```
It appears that del*_on_destroy must be before the volumes, not after.

The values are respected, and the volumes are deleted on destroy. This is financially dangerous, as the failure is completely silent, and leads to orphaned EBS volumes. In our case, I had to clean up several hundred.
